### ISSUE TITLE
CSS Error when HTTP-Header Login

### ISSUE THREAD

**Issue by madmexx2002** [flowsforapex/apex-flowsforapex#333]
Hello

When the authentication schema is switched to HTTP-Header (SSO) some colors are wrong, using the wrong class. 
Currently i am using Apex 20.1 with F4A 21.1. I haven't found the error yet.

![F4A_WRONG_COLORS](https://user-images.githubusercontent.com/36326420/134904575-877bbcbd-d10e-4d5b-8912-c4d93a74c8cb.PNG)
e.

**Comment by madmexx2002** [comment]
Found a solution. Took Page Process "Set Theme Mode" from page 9999 and put it into the Post-Authentication Procedure and made a user preference for the last selected theme. Only the automatic mode is still a problem, don't know how to handle the media query (javascript) during authentication.

**Comment by damthor** [comment]
Hi, you're right, moving the "Set Theme Mode" Process from the Login page could help solving the problem. Whereas I currently don't see any solution for the automatic mode, because we need the JS context there for retrieving the preferred color scheme using window.matchMedia. Calling this only on page load would be too late so you'd need a page refresh after it anyhow. Best workaround I see right now for that: adding a default fallback to "Set Theme Mode", so it can be used without the page variable from p.9999 and automatic mode can only be used if a user selects it after login on the navigation bar menu.

**Comment by madmexx2002** [comment]
Hi Dennis

What about a media query on the global page? If the current setting is the same don't do anything else submit with the same REQUEST like u do in the menubar.

**Comment by damthor** [comment]
Good idea using the global page for that. I tried it out and got it working like this:
- move page item + dynamic action to retrieve os setting to global page
- move process for setting the theme based on user/os setting to application process, executed after authentication
This way we totally keep p.9999 clear from that, which should allow other authentication modes.

**Comment by madmexx2002** [comment]
Well done :)

**Comment by madmexx2002** [comment]
One more thing. Is the application process (after authentication) execution point really after global page is loaded? Didn't found a answer in the documentation...

**Comment by damthor** [comment]
I was only able to try it with the default authentication using an APEX user, so don't know for sure if that's the case for all authentication types. But if not, I don't see any way to execute that JS snippet for retrieving the OS setting somewhere before the authentication is done.

**Comment by damthor** [comment]
Quick update: tested it with open door authentication scheme. The "After Authentication" process indeed executes **before** the global page is loaded. On the other hand, any other executions points like "Before Header" oder "AJAX" (called from the DA on the global page) set the theme settings too late, so a manual refresh of the page is necessary to set the correct theme mode.
