### ISSUE TITLE
[bug]: incomplete toolbar is displayed

### ISSUE THREAD

**Issue by sbarry0317** [flowsforapex/apex-flowsforapex#456]
### Flows for APEX version

22.1 (latest release)

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

i am working  thru first tutorial. 'getting started' i am working in apex.oracle.com workspace. The complete toolbar doesn't dispay. I cannot view everything below the 'create gateway' icon. Thanks for any help you can provide.
[incomplete_toolbar.docx](https://github.com/flowsforapex/apex-flowsforapex/files/8622388/incomplete_toolbar.docx)

**Comment by damthor** [comment]
Hi,

thanks for reporting. This looks like an error caused by the responsive design of the modeler tools palette. By default, all the icons are displayed below each other, if there is enough space. On smaller screens they move into the two-column layout.
It also could be a browser-specific issue. What browser (+ version) are you using? Did you already try using a different browser or do you have the possibility to try a different screen resolution?
If the problem is still existing, maybe you could give me access to your app, then I can see what's causing the problem.

Regards,
Dennis
