### ISSUE TITLE
Automatically approved 

### ISSUE THREAD

**Issue by fahadrafique** [flowsforapex/apex-flowsforapex#472]
Hi, 
We have been using flowforapex from past two years with 5 layers of roles and encountered no issues.
But recently flow is automatically approving all steps till the end. Even there is no update or changed applied on our production environment related to work flow. Since we are using version 5 and never updated because it was working perfectly.

Could there be any reason behind it which is causing trigger to process all steps automatically?

**Comment by rallen2010** [comment]
Customer is running v5.0.0. (Dec 2020)
After looking at system, we strongly suspect that he needs Immediate solution by taking the 5.0.1 patch release.(Jan 2020) to prevent issues from objects or connections in other diagrams having the same dgrm_id.  This was identified and fixed in 5..0.1.
As a mid-term solution, we would recommend upgrading to a more current release (e.g., 22.1) as 5.0. is now 4 releases ago.

**Comment by rallen2010** [comment]
Confirmed that this solution worked and resolved the immediate issue.
