### ISSUE TITLE
[bug]: flow_instance_diagrams needs tree of instance diagram id's

### ISSUE THREAD

**Issue by rallen2010** [flowsforapex/apex-flowsforapex#479]
### Flows for APEX version

22.2 (development)

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

Call Activity Nesting:  Flow_instance_diagrams can return almost duplicate rows (only diff is prdg_id) with complex models repetitively calling same models, meaning that you can't find a child or parent diagram.  Need to create a tree of prdg_id's by creating & maintaining a parent prdg_id (add column prdg_prdg_id).

**Comment by damthor** [comment]
Changes need to be reflected in the viewer too. Otherwise it can't be guaranteed, that the viewer shows the correct diagram instance (esp. in terms of highlighting).

Planned changes:

- Extend all page views + flow_instance_details_vw to include prdg_id and prdg_prdg_id
- Rework viewer attributes (diagram id and calling diagram) to generic diagram identifier and calling diagram identifier. For running instances this will be prdg_id and prdg_prdg_id, otherwise dgrm_id and calling_dgrm (as before).
- Update viewer to use the new attributes
- Update dynamic actions depending on the viewer events + return values

**Comment by damthor** [comment]
Solved in https://github.com/flowsforapex/apex-flowsforapex/pull/494
