### ISSUE TITLE
[bug]: Database 23c Free: ORA-01403: no data found after start a flow

### ISSUE THREAD

**Issue by ljvankempen** [flowsforapex/apex-flowsforapex#675]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

23c

### Oracle APEX version

23.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

No

### What happened?

 
![image](https://github.com/flowsforapex/apex-flowsforapex/assets/76656018/a6c66ffb-5021-4a74-8082-0a1f29414aae)

### Steps to reproduce

Start / Run  a flow.

Happens on all flows

### Expected behaviour

THat it runs without error.

Nothing to find in the alert-log

**Comment by rallen2010** [comment]
can we have a quick zoom call to see / help?  Email me at Richard.allen@ora***.com

**Comment by rallen2010** [comment]
These problems replicate on database 23c, which is not yet production.  There are currently a few issues running on 23c, and we have not yet been able to fix and fully test these.  We will do more testing as 23c becomes available.

**Comment by rallen2010** [comment]
This issue is a database issue in 23c 23.3.0.   A workaround has been incorporated into a patch for Flows for APEX 23.1 which avoids this problem.  
Hotfix file `combo-fix-675-676-681.sql` is available as a Release 23.1 asset at https://github.com/flowsforapex/apex-flowsforapex/releases/tag/v23.1  and which addresses this issue and provides support for Oracle Database 23c (23.3.0).  This patch has been tested on both 19c and 23c (23.3.0) databases, including 23c Free (23.3.0).
